[#gonext]
=== Добавление учётных данных
После нажатия кнопки *Создать* откроется страница для добавления учётных данных. Здесь сложностей быть не должно.

Нужно выполнить следующие действия:

. Ответить на вопрос: *"Какой API вы используете?"*
+
Очевидно, мы используем Cloud Translation API.
+
[#engines]
. Ответить на вопрос (_может не появиться, это нормально_): *"Планируется ли иcпользовать этот API для App Engine или Compute Engine?"*.
+
Выбрать "Нет". Все эти Engines для бытового применения не нужны.
+
. Ответить на вопрос: *"С какими данными вы будете работать?"* +
+
Ответить *"С данными приложения"*.
+
. После этого может быть предложено ответить на вопрос из <<engines,пункта 2>>.
+
Ответить отрицательно.
+
. Нажать на кпопку *Выбрать тип учётных данных*. Кнопка может также называться *Далее*.
+
Развернётся следующий пункт -- *Создание сервисного аккаунта*.
+
. Дальнейшие действия могут различаться:
+
* Раньше нужно было выбрать роль *Проект* -> *Владелец* из раскрывающегося списка, потом выбрать тип ключа и т.д.

* Сейчас нужно ввести имя сервисного аккаунта, его описание и нажать *Создать*.

. А следующие шаги вообще опциональны и их можно пропустить:

* Дать сервисному аккаунту права доступа к проекту.
* Дать пользователям доступ к этому сервисному аккаунту.
+
. Нажать кнопку *Готово*.
+
Откроется страница учётных данных.
+
. На странице учётных данных нужно нажать кнопку *+ Создать* (*Create Credentials*).
[#keyGenerated]
. В появившемся меню выбрать *Ключ API*.
+
Откроется окно с готовым ключом API. Можно ограничить доступ к ключу, чтобы его никто не похитил и не начал использовать для перевода многих сотен миллионов символов. Но проще просто не передавать ключ никому. Кто-то просит ключ? Пусть создаст себе свой. Это несложно.

Итак, ключ создан. Не нужно записывать этот ключ на бумажку или сохранять в файл. Ключ всегда доступен для копирования из {gcc}. Чтобы копировать ключ, нужно перейти на главную страницу {gcc}, затем навести мышку на APIs & Sercvices, а потом выбрать Credentials. Все ключики будут показаны на экране.
Теперь его можно использовать, но пока что негде. Значит пора переходить к настройке {mc}.