
== Введение

[#top]
Если содержание уже пугает, то советую прочитать краткую информацию вот в <<indoubt,этом пункте>>.

=== Что такое {mc}?

{mc} - это бесплатная утилита для переводов. Основные преимущества:

- бесплатность,
- скорость работы,
- простота использования,
- богатый набор функций, включая интеграцию с машинным переводом и работу с гуглодиском

Подкупает именно возможность бесплатно работать одновременно с гуглодиском, машинным переводом. При этом настроить всю шушуеру не составит труда.

[#srsly]
=== Почему машинный перевод?

Я предлагаю для перевода в {mc} использовать машинный перевод, потому что он облегчает жизнь.

Но машинный перевод делает очень много ошибок, он совсем плохой и смешной. Любой сможет отличить машинный перевод от человеческого.

На самом деле - это миф. Да, гугл переводчик может выдать ошибки, но это устаревшая информация и ошибки несерьёзные.

Я пользуюсь машинным переводом почти всегда, когда мне нужно перевести хоть сколько объёмный текст, т.к. это упрощает и ускоряет процесс. После современного машинного перевода даже мне остаётся только немного отредактировать, а я всё-таки являюсь некоторым специалистом в этой области.  Так что для бытовых целей машинный перевод от гугла подойдёт отлично.