:author: Маркиев Владимир
:sectids:
:sectanchors:
:sectlinks:
:sectnums:
:sectnumlevels: 5
:toc:
:toclevels: 5
:toc-title: Содержание:
:icons: font
:imagesdir: C:\Users\Vladimir\Desktop\Manual
:mc: MateCat
:gcp: Google Cloud Platform
:gcc: Google Cloud Console
:any: любое, хоть "Единороги скачут по радуге", если потом это имя не вызовет путаницу
= Как переводить тексты при помощи {mc}

[#top]
Если содержание уже пугает, то советую прочитать краткую информацию вот в <<indoubt,этом пункте>>.

== Введение

=== Что такое {mc}

{mc} - это бесплатная утилита для переводов. Основные преимущества:

- бесплатность,
- скорость работы,
- простота использования,
- богатый набор функций, включая интеграцию с машинным переводом и работу с гуглодиском

Подкупает именно возможность бесплатно работать одновременно с гуглодиском, машинным переводом. При этом настроить всю шушуеру не составит труда.

=== Машинный перевод! Какой ужас!
На самом деле - это миф. Да, гугл переводчик может выдать ошибки, но это устаревшая информация и ошибки несерьёзные.

Я пользуюсь машинным переводом почти всегда, когда мне нужно перевести хоть сколько объёмный текст, т.к. это упрощает и ускоряет процесс. После современного машинного перевода даже мне остаётся только немного отредактировать, а я всё-таки являюсь некоторым специалистом в этой области.  Так что для бытовых целей машинный перевод от гугла подойдёт отлично.