=== Регистрация в {gcp}
Машинный перевод настраивается через Google Cloud Platform, для которой нужен гугл аккаунт. Если гуглоаккаунта ещё нет или не хочется использовать основной, можно зарегистрировать ещё один, инструкции доступны в интернете.

. Первым делом необходимо перейти в https://console.cloud.google.com/[{gcc}].
+
[NOTE]
Чтобы начать работать с {gcp} нужно перейти в {gcc} - это немного сбивает с толку, но так вот гугл придумал.
+
Гугл предложит ознакомиться с условиями предоставления услуг. Можно ознакомиться при желании, а можно просто принять условия.
Соглашаться на рассылку необязательно.
+
. После ознакомления нажать *Agree And Continue*.
+
Наверху появится уведомление с предложением активировать подарок. Нужно нажать *Activate*.
. Будет открыта новая страница, где нужно снова ознакомиться с условиями и принять их. Нажать *Принять и продолжить*.
. Откроется следующая страница *Шаг 2 из 2*.
+
На этой странице нужно заполнить все поля настоящей информацией.
+
.. В разделе *Тип аккаунта* выбрать ничего нельзя, поэтому оставляем бизнес.
+
.. В разделе *Наименование и адрес* нужно указать что-нибудь типа *Моя лучшая компания*, в трёх строках адреса можно написать свой домашний адрес.
+
Где это возможно, заполнять поля важно реальной информацией, чтобы пройти проверку.
+
.. Потом нужно заполнить раздел *Основной контакт* своими контактными данными и перейти к разделу оплаты.
.. В разделе оплаты нужно заполнить данные банковской карты.
+
[IMPORTANT]
Заполнить данные банковской карты придётся в любом случае. Данные должны быть настоящими, отвертеться не получится. Но не стоит пугаться, всё нормально, гугл не будет списывать деньги за перевод в объёмах до 250 миллионов символов в месяц. Это очень большой лимит. Когда я постоянно переводил, у меня не получалось его превысить. К тому же гугл даёт возможность израсходовать 300 долларов просто по доброте душевной.
+
После успешного завершения регистрации необходимо перейти к следующей части.