:author: Маркиев Владимир
:sectids:
:sectanchors:
:sectlinks:
:sectnums:
:sectnumlevels: 5
:toc:
:toclevels: 5
:toc-title: Содержание:
:icons: font
:imagesdir: C:\Users\Vladimir\Desktop\Manual
:mc: MateCat
:gcp: Google Cloud Platform
:gcc: Google Cloud Console
= Как переводить тексты при помощи {mc}

[#top]
Если содержание уже пугает, то советую прочитать краткую информацию вот в <<indoubt,этом пункте>>.

== Что такое {mc}

{mc} - это бесплатная утилита для переводов. Основные преимущества:

- бесплатность,
- скорость работы,
- простота использования,
- богатый набор функций, включая интеграцию с машинным переводом и работу с гуглодиском

Подкупает именно возможность бесплатно работать одновременно с гуглодиском, машинным переводом. При этом настроить всю шушуеру не составит труда.

== Настройка машинного перевода
Я предлагаю использовать машинный перевод от гугла, потому что его проще настроить. Для этого понадобится получить один ключ, потом добавить его в настройки {mc}. Это совсем не страшно.

Конечно, проще было бы мне дать использовать свой ключ и свой аккаунт, но лучше иметь все свои настройки на случай, если что-то поменяется.

=== Машинный перевод! Какой ужас!
На самом деле - это миф. Да, гугл переводчик может выдать ошибки, но это устаревшая информация и ошибки несерьёзные.

Я пользуюсь машинным переводом почти всегда, когда мне нужно перевести хоть сколько объёмный текст, т.к. это упрощает и ускоряет процесс. После современного машинного перевода даже мне остаётся только немного отредактировать, а я всё-таки являюсь некоторым специалистом в этой области.  Так что для бытовых целей машинный перевод от гугла подойдёт отлично.

=== Регистрация в {gcp}
Машинный перевод настраивается через Google Cloud Platform, для которой нужен гугл аккаунт. Если гуглоаккаунта ещё нет или не хочется использовать основной, можно зарегистрировать ещё один, инструкции доступны в интернете.

. Первым делом необходимо перейти в https://console.cloud.google.com/[{gcc}].
+
[NOTE]
Чтобы начать работать с {gcp} нужно перейти в {gcc} - это немного сбивает с толку, но так вот гугл придумал.
+
Гугл предложит ознакомиться с условиями предоставления услуг. Можно ознакомиться при желании, а можно просто принять условия.
Соглашаться на рассылку необязательно.
+
. После ознакомления нажать *Agree And Continue*.
+
Наверху появится уведомление с предложением активировать подарок. Нужно нажать *Activate*.
. Будет открыта новая страница, где нужно снова ознакомиться с условиями и принять их. Нажать *Принять и продолжить*.
. Откроется следующая страница *Шаг 2 из 2*.
+
На этой странице нужно заполнить все поля настоящей информацией.
+
.. В разделе *Тип аккаунта* выбрать ничего нельзя, поэтому оставляем бизнес.
+
.. В разделе *Наименование и адрес* нужно указать что-нибудь типа *Моя лучшая компания*, в трёх строках адреса можно написать свой домашний адрес.
+
Где это возможно, заполнять поля важно реальной информацией, чтобы пройти проверку.
+
.. Потом нужно заполнить раздел *Основной контакт* своими контактными данными и перейти к разделу оплаты.
.. В разделе оплаты нужно заполнить данные банковской карты.
+
[IMPORTANT]
Заполнить данные банковской карты придётся в любом случае. Данные должны быть настоящими, отвертеться не получится. Но не стоит пугаться, всё нормально, гугл не будет списывать деньги за перевод в объёмах до 250 миллионов символов в месяц. Это очень большой лимит. Когда я постоянно переводил, у меня не получалось его превысить. К тому же гугл даёт возможность израсходовать 300 долларов просто по доброте душевной.
+
После успешного завершения регистрации необходимо перейти к следующей части.

=== Создание проекта в {gcc}
После регистрации система сама перенаправит на нужную страницу, но если этого не произошло, то нужно ещё раз ввести адрес https://console.cloud.google.com/[{gcc}].

Чтобы создать проект, необходимо выполнить следующее:

. На синей полоске в верхней левой области страницы найти *My First Project*, раскрыть меню, в появившемся окошке выбрать *Создать проект*.
. Ознакомиться с информацией на странице, при желании изменить название проекта. Местоположение проекта менять не требуется. После ознакомления нажать *Создать*.
+
Снова откроется главная страница {gcc}, но уже для другого проекта.
+
Чтобы убедиться, в том, что проект правильный, нужно посмотреть на синюю полоску в верхней левой области страницы. Если там указано имя нужного проекта, то всё замечательно. В противном случае нужно выбрать проект с правильным именем.
. Затем нужно открыть меню, нажав кнопку в левом верхнем углу страницы. В меню выбрать пункт API и сервисы.
. На следующей странице нажать на кнопку *+ Включить API и сервисы*.
+
Откроется библиотека API. Всё нормально.
. В строке поиска набрать *Cloud Translation API*, если его нет на главной странице. Перейти на страницу API.
. На странице *Cloud Translation API* в разделе *Стоимость* выбрать модель оплаты.
+
[WARNING]
Из всех моделей оплаты нужна та, которая называется *AutoML Translation Online Predictions*. Именно она будет бесплатной, если не переводить больше 250 миллионов символов.
+
. После выбора модели оплаты, нажать синюю кнопку *Включить*.
+
Система скажет, что для использования этого API нужно создать учётные данные (Credentials).
+
Если система не предлагает создать учётные данные, а предлагает создать платёжный аккаунт (Billing account), его просто нужно выбрать из раскрывающегося списка. Он будет под названием *My Billing Account*.

=== Создание учётных данных
Если на экране появилась страница с запросом создать учётные данные, нужно их создать. Для этого нужно нажать кнопку *Создать* (*Create Credentials*) в правом верхнем углу страницы.

Если закрались сомнения, рекомендую прочитать пункт <<indoubt,Закрались сомнения>>. Если пока сомнений нет, можно сразу перейти <<gonext,дальше>>. Если совсем ничего не понятно, рекомендую начать <<top,сначала>>.

[#indoubt]
==== Закрались сомнения?
Где-то на этом моменте могут появиться сомнения. На всякий случай разберу несколько логичных вопросов в формате вопрос/ответ:

В: Зачем мне всё это? +
О: Чтобы настроить машинный перевод и не тратить лишние силы и время.

В: Почему так сложно? +
О: Да, эта часть может показаться сложно, но если следовать инструкции проблем не возникнет. В следующий раз будет проще. Ну и ещё это полезное знание.

В: А что если с меня спишут все деньги? +
О: Не спишут. Нужно понимать, что пока мы ничего не делаем, мы ничего не платим. Создание ключа - бесплатное. Можно выбрать даже самый дорогой тарифный план, но пока что мы ни за что не платим.

[#gonext]
=== Добавление учётных данных
После нажатия кнопки *Создать* откроется страница для добавления учётных данных. Здесь сложностей быть не должно.

Нужно выполнить следующие действия:

. Ответить на вопрос: *"Какой API вы используете?"*
+
Очевидно, мы используем Cloud Translation API.
+
[#engines]
. Ответить на вопрос (_может не появиться, это нормально_): *"Планируется ли иcпользовать этот API для App Engine или Compute Engine?"*.
+
Выбрать "Нет". Все эти Engines для бытового применения не нужны.
+
. Ответить на вопрос: *"С какими данными вы будете работать?"* +
+
Ответить *"С данными приложения"*.
+
. После этого может быть предложено ответить на вопрос из <<engines,пункта 2>>.
+
Ответить отрицательно.
+
. Нажать на кпопку *Выбрать тип учётных данных*. Кнопка может также называться *Далее*.
+
Развернётся следующий пункт -- *Создание сервисного аккаунта*.
+
. Дальнейшие действия могут различаться:
+
* Раньше нужно было выбрать роль *Проект* -> *Владелец* из раскрывающегося списка, потом выбрать тип ключа и т.д.

* Сейчас нужно ввести имя сервисного аккаунта, его описание и нажать *Создать*.

. А следующие шаги вообще опциональны и их можно пропустить:

* Дать сервисному аккаунту права доступа к проекту.
* Дать пользователям доступ к этому сервисному аккаунту.
+
. Нажать кнопку *Готово*.
+
Откроется страница учётных данных.
+
. На странице учётных данных нужно нажать кнопку *+ Создать* (*Create Credentials*).
. В появившемся меню выбрать *Ключ API*.
+
Откроется окно с готовым ключом API. Можно ограничить доступ к ключу, чтобы его никто не похитил и не начал использовать для перевода многих сотен миллионов символов. Но проще просто не передавать ключ никому. Кто-то просит ключ? Пусть создаст себе свой. Это несложно.

Итак, ключ создан. Теперь его можно использовать, но пока что негде. Значит пора переходить к настройке {mc}.

== Настройка {mc}
Настроить {mc} проще, чем {gcp}.

Для этого нужно следующее:

. Перейти на главную страницу {mc} - https://www.matecat.com/[{mc}.com].
. В правом верхнем углу страницы нажать на иконку человечка.
+
Откроется окошко входа. +
 +
На регистрацию можно забить, ведь у нас есть гуглоаккаунт!
+
. Выбрать Sign in with Google.
. Затем выбрать свой гуглоаккаунт и разрешить доступ к аккаунту в новом окне, нажав *Разрешить*. или *Allow*.
. {mc} предложит сгенерировать ключ API для аккаунта, но нам это не нужно. А вот доступ к гуглодиску пригодится, поэтому ставим переключатель под Google Drive в положение *ON*.
. Откроется новое окно для выбора аккаунта. Это нормально, выбираем









