== Перевод текста при помощи {mc}

=== Настройка проекта
Прежде чем переводить текст, потребуется создать проект. Это совсем не сложно.

На главной странице {mc}:

В поле `Project name` нужно указать имя проекта. Имя лучше вводить латинскими буквами, без пробелов и специальных символов, кроме нижнего подчёркивания (_) и дефиса (-) Иначе {mc} может работать некорректно.

Список *From* содержит языки, с которых можно перевести документ. Если перевод с английского, нужно выбрать любой English доступный в списке.

Аналогично поступить со списком *To*.

В списке *Select subject* нужно выбрать тему перевода. Это не обязательно, но рекомендуется.

В списке TM & Glossary можно ничего не выбирать, тогда по умолчанию будет использоваться общая для всего {mc} память переводовfootnote:[Что такое память переводов, можно посмотреть в интернете.]. Можно создать свою собственную память переводов, нажав на кнопку *Create resource* -> *New resource*. А можно импортировать уже существующую, нажав *Import TMX*.footnote:[Вряд ли такие детали понадобятся при обычном бытовом переводе, но знать полезно.]