=== Перевод документа в {mc}
После того как все поля проекта заполнены, можно начинать работу с файлами из гуглодиска.

[NOTE]
Лучше отключить AdBlock на сайте {mc}. Иначе он может работать некорректно.

Для этого:

.  Под надписью *"Drop your files to translate them with MateCat"* нужно найти фразу *"MateCat supports 78 file formats and Google Drive files"* и нажать на ссылку *Google Drive files*.
+
Откроется окошко гуглодиска.
+
. Нужно выбрать файл(ы) из гуглодиска, затем нажать *Select*.
+
[IMPORTANT]
Поддерживаются только файлы в формате гуглодиска. Это значит, что любой формат, который не был изначально создан в гуглодиске, не получится добавить на перевод. Обходное решение -- скопировать всё содержимое документа в любом формате и вставить его в новый документ на гуглодиске. Структура документа от этого не пострадает.
+
. После добавления документов нужно нажать кнопку *Analyze*.
+
В новой вкладке откроется страница анализа проекта, нужно нажать *Translate*.

Благодаря подключенному машинному переводу {mc} автоматически подставит перевод в каждый сегмент. Останется только посмотреть каждый сегмент и, при желании, отредактировать неточности.

Если {mc} не подставил перевод, нужно пройтись по каждому сегменту и выбрать перевод вручную.